### ISSUE TITLE
is this working ?

### ISSUE THREAD

**Issue by abdolrhman** [Akumzy/socket.io-file-stream#1]
hey buddy is this working ?

**Comment by Akumzy** [comment]
Yes it does but I switched ffrom using ReadableStream to  rxjs Observable which gives me more flexibility over ReadableStream 
 You can check it [@akumzy/socket.io-stream](https://github.com/Akumzy/socket.io-stream) I didn't want to break an app that depends on this package so I created a new package.

**Comment by abdolrhman** [comment]
@Akumzy Great thanks buddy,
am new to stream with socket.io ,
I am wondering is it possible, to download a file via ftp and then stream the state of this file being download (percentage, remaining ) to front-end ??
i appreciate a lot your help

**Comment by Akumzy** [comment]
Yes but don't need socket stream for that if it's just send download progress at the server to client.

**Comment by abdolrhman** [comment]
@Akumzy , Can u clarify more please ??
i mean what i have done now, is 
- build a function to download a file via FTP it connect to the other server via ftp if it found a new file it download it to the local server,
- during the file being downloaded how to push the state of the file being download ( remain , precenegtege ) to the front-end , thats all my problem right now how to make a progress bar in a front end to show the file being download with its ramining percentege ?

thank you very much for your response it really means alot to me :)

**Comment by Akumzy** [comment]
@abdolrhman  you can implement it this way 
Disclaimer: I didn't test the code it's just for illustration 

```js
const progress = require('progress-stream');
const fs = require('fs');
const Client = require('ftp');

const c = new Client();

// connect to localhost:21 as anonymous
c.connect();
c.on('ready', function() {
    c.get('foo.txt', function(err, stream) {
        if (err) throw err;
        var str = progress({
            length: filesize,
            time: 100 /* ms */
        });
         
        str.on('progress', function(progress) {
            console.log(progress);
            // Emit the event to your frontend
            io.socket.emit('send-progress-to-client', progress)
            /*
            {
                percentage: 9.05,
                transferred: 949624,
                length: 10485760,
                remaining: 9536136,
                eta: 42,
                runtime: 3,
                delta: 295396,
                speed: 949624
            }
            */
        });
      stream.once('close', function() { c.end(); });
      stream.pipe.pipe(str)(fs.createWriteStream('foo.local-copy.txt'));
    });
  });
```

**Comment by abdolrhman** [comment]
dude, first of all you don't how much this means to me,
i was really in a maze i didnt know how to connect the dots at all,

but now i can see what are your trying to show me,
if is it possible can u explain more, this is what i am using from what u gave me my friend
```
const progress = require('progress-stream');
const fs = require('fs');
const Client = require('ftp');
var log = require('single-line-log').stdout;
var numeral = require('numeral');
const io = require('socket.io').listen(8000);

const c = new Client();

// connect to localhost:21 as anonymous
c.connect({
  user: 'mypc',
  password: 'mypassword'
});
c.on('ready', function() {
    console.log(__dirname)
    c.get(__dirname + '/file.txt', function(err, stream) {
        if (err) throw err;
        var str = progress({
            time: 10 /* ms */
        });
         
        str.on('progress', function(progress) {
           console.log(progress);
            // Emit the event to your frontend
            io.sockets.emit('send-progress-to-client', progress)
            /*
            {
                percentage: 9.05,
                transferred: 949624,
                length: 10485760,
                remaining: 9536136,
                eta: 42,
                runtime: 3,
                delta: 295396,
                speed: 949624
            }
            */
        });
      stream.once('close', function() { c.end(); });
      const dest = fs.createWriteStream('foo.local-copy.txt')
      stream.pipe(str).pipe(dest);
    });
  });
```
the problem is at the moment i fire the code i got this in console

> { percentage: 100,
  transferred: 9400,
  length: 0,
  remaining: 0,
  eta: 0,
  runtime: 0,
  delta: 9400,
  speed: 9400 }

i expected i will get like many objects in which each will have like {precenetge: 1 ...} {precentege: 2 ...} etc 
but it gave me one object it once, is this because its fast its local, or should i add some configuration ,

also can i send u invitation in hangout , thanks buddy for every thing, god bless u

**Comment by Akumzy** [comment]
@abdolrhman No it's not giving your all at once if you check my example you'll see that I provided a length property to `progress` function
```js
  var str = progress({
            length: filesize,
            time: 100 /* ms */
        });
         
```
You'll need a way to get the actual file you're downloading size somehow that's the only way for it to work

**Comment by Akumzy** [comment]
Do this @abdolrhman

```js
const progress = require('progress-stream')
const fs = require('fs')
const Client = require('ftp')

class FTP extends Client {
  constructor() {
    super()
  }
  sizeAsync(path) {
    return new Promise((resolve, reject) => {
      this.size(path, (err, size) => (err ? reject(err) : resolve(size)))
    })
  }
  getAsync(path) {
    return new Promise((resolve, reject) => {
      this.get(path, (err, stream) => (err ? reject(err) : resolve(stream)))
    })
  }
}
// var log = require('single-line-log').stdout;
// var numeral = require('numeral');
// const io = require('socket.io').listen(8000);

const c = new FTP()

// connect to localhost:21 as anonymous
c.connect({
  host: 'example.com',
  user: 'user',
  password: 'password',
})
c.on('ready', async function() {
  try {
    const fileSize = await c.sizeAsync('cloud-app/cloud-app.zip')
    console.log(fileSize)
    const stream = await c.getAsync('cloud-app/cloud-app.zip')
    const str = progress({
      length: fileSize,
      time: 10 /* ms */,
    })
    str.on('progress', function(progress) {
      console.log(progress)
      // Emit the event to your frontend
      // io.sockets.emit('send-progress-to-client', progress)
      /*
              {
                  percentage: 9.05,
                  transferred: 949624,
                  length: 10485760,
                  remaining: 9536136,
                  eta: 42,
                  runtime: 3,
                  delta: 295396,
                  speed: 949624
              }
              */
    })
    stream.once('close', function() {
      c.end()
    })
    const dest = fs.createWriteStream('foo.local-copy.zip')
    stream.pipe(str).pipe(dest)
  } catch (error) {
    console.error(error)
  }
})

```

**Comment by abdolrhman** [comment]
@Akumzy  buddy, its working like a charm, 
i really don't know what to tell you,
your help means alot to me, i searched alot, i found many resource but i couldnt know how to connect things, really thank you buddy :)) 

there is some thing was thinking about, is there a way to continue to download the file in the last state where the service stopped , i mean if it were 30% then i stoped the service is there a way to continue from this 30% ?

again thank you, and if it possible to guild me to good resource where i can understand the core of this things so i can easly connect the dots , like you did, 

thanks buddy one more time :)

**Comment by Akumzy** [comment]
With ftp? I don't know if file read offset is possible.
@abdolrhman you can added me on Twitter [DeAkumzy](https://twitter.com/DeAkumzy) further more questions.

**Comment by abdolrhman** [comment]
@Akumzy hey bro,
is there a way to run a cron job over this, i have a lots of files in which they are being added during time,
so i want to build a cron or queue in which it download files in all of this queue, 
any idea bro ?
thank you ^^

**Comment by Akumzy** [comment]
Sure  I'm open for hire me.

**Comment by abdolrhman** [comment]
am sorry bro this may upset you that i asked ur help mich
i didnt mean to dissrepect u or any thing . am gust junior dev . who is
gust looking for help. mainly because no one does
i really really apperciate ur help.
 please do accept my appology
 and have a great night :)

**Comment by Akumzy** [comment]
No problem bro, If you're on discord or twitter you can send me a message I'll be happy to assist if I less busy but using Github issues for something like this is not he best way.

**Comment by abdolrhman** [comment]
Thanks buddy,
Again please accept my apology,
this is my discord : 
Nasr
#9879

Your a good man, thank you for all ur help :)
